version: '3'

services:
  leaderboard-docker:
    build: .
    container_name: leaderboard-docker
    volumes:
      - .:/home/node/api
      - /home/node/api/node_modules
    ports:
      - '3333:3333'
    depends_on: 
      - learning-redis
    networks:
      - leaderboard-networks
  learning-redis:
    image: bitnami/redis
    container_name: learning-redis
    environment: 
      - ALLOW_EMPTY_PASSWORD=no
      - REDIS_PASSWORD=${REDIS_PASSWORD}
    volumes:
      - learning-redis-data
    networks:
      - leaderboard-networks
volumes:
  learning-redis-data:
networks:
  leaderboard-networks:
    driver: bridge